import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col p-0 m-0">
        <Navbar />
        <div style={{ flex: 1 }}>
          {children}
        </div>
        <footer style={{
          background: '#001f3f',
          color: '#8a9bb0',
          textAlign: 'center',
          padding: '24px 16px',
          fontSize: '0.9rem',
          marginTop: 'auto',
          fontFamily: 'var(--font-geist-sans), sans-serif',
        }}>
          <p style={{ margin: '0 0 4px', fontWeight: 600, color: '#fff' }}>Daniel Vasquez - VV232745</p>
          <p style={{ margin: 0 }}>DPS104 G03L</p>
        </footer>
      </body>
    </html>
  );
}
